$(document).ready(()=>{
		$("#navbar-menuId").show();
		$("#aboutContent").hide();
		$("#careersContent").hide();
		$("#flex-helpContent").hide();
	$("#minimizedlineId").click(()=>{
		$("#homeId").toggle();
		$("#aboutId").toggle();
		$("#careersId").toggle();
		$("#flex-help").toggle();
		/*$(".navbar-menu").toggle();*/
	})
	$("#navbar-menuId").click(()=>{
		$("#homeContent").show();
		$("#aboutContent").hide();
		$("#careersContent").hide();
		$("#flex-helpContent").hide();
	})
	$("#homeId").click(()=>{
		$("#homeContent").show();
		$("#aboutContent").hide();
		$("#careersContent").hide();
		$("#flex-helpContent").hide();
	})
	$("#aboutId").click(()=>{
		$("#homeContent").hide();
		$("#aboutContent").show();
		$("#careersContent").hide();
		$("#flex-helpContent").hide();
	})
	$("#careersId").click(()=>{
		$("#homeContent").hide();
		$("#aboutContent").hide();
		$("#careersContent").show();
		$("#flex-helpContent").hide();
	})
	$("#flex-help").click(()=>{
		$("#homeContent").hide();
		$("#aboutContent").hide();
		$("#careersContent").hide();
		$("#flex-helpContent").show();
	})
})